name: CI

on: [ pull_request ]

jobs:
  run-maven-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: My Kubernetes version
      run: kubectl config view
    
    - name: Run build
      run: mvn clean install
    
